doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            EmployeeEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/Employee/Entity'
                prefix: App\Employee\Domain\Entity
            BusinessTripEntity:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/BusinessTrip/Entity'
                prefix: App\BusinessTrip\Domain\Entity
            BusinessTripValueObject:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/BusinessTrip/ValueObject'
                prefix: App\BusinessTrip\Domain\ValueObject

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system