employee-add:
  path: /employees
  controller: App\UserInterface\Api\Controller\EmployeeController::add
  methods: POST

employee-business-trip-add:
  path: /employees/{employeeId}/business-trips
  controller: App\UserInterface\Api\Controller\BusinessTripController::add
  methods: POST
  requirements:
    employeeId: '\S+'

employee-business-trip-list:
  path: /employees/{employeeId}/business-trips
  controller: App\UserInterface\Api\Controller\BusinessTripController::list
  methods: GET
  requirements:
    employeeId: '\S+'
